ARG ALPINE_VERSION=3.20.1
ARG KEYCLOAK_VERSION=25.0.1
FROM alpine:$ALPINE_VERSION AS fipsJarDownloader

# Set the working directory
WORKDIR /tmp/fips-jars

# Bouncy Castle JAR versions to download
ARG BC_FIPS_VERSION=1.0.2.5
ARG BCTLS_FIPS_VERSION=1.0.19
ARG BCPKIX_FIPS_VERSION=1.0.7

ARG BC_MAVEN_URL=https://repo1.maven.org/maven2/org/bouncycastle

# Download Bouncy Castle JAR files
RUN apk upgrade --no-cache && apk --no-cache add curl \
 && curl -O ${BC_MAVEN_URL}/bc-fips/${BC_FIPS_VERSION}/bc-fips-${BC_FIPS_VERSION}.jar \
 && curl -O ${BC_MAVEN_URL}/bctls-fips/${BCTLS_FIPS_VERSION}/bctls-fips-${BCTLS_FIPS_VERSION}.jar \
 && curl -O ${BC_MAVEN_URL}/bcpkix-fips/${BCPKIX_FIPS_VERSION}/bcpkix-fips-${BCPKIX_FIPS_VERSION}.jar

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION as builder

ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=scripts,token-exchange,admin-fine-grained-authz,fips
ENV KC_FIPS_MODE=strict

COPY --chown=keycloak:keycloak --from=fipsJarDownloader /tmp/fips-jars/ /opt/keycloak/providers/
COPY --chown=keycloak:keycloak libs/folio-scripts.jar /opt/keycloak/providers/
COPY --chown=keycloak:keycloak conf/* /opt/keycloak/conf/
COPY --chown=keycloak:keycloak cache-ispn-jdbc.xml /opt/keycloak/conf/cache-ispn-jdbc.xml

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

COPY --from=builder --chown=keycloak:keycloak /opt/keycloak/ /opt/keycloak/

RUN mkdir /opt/keycloak/bin/folio
COPY --chown=keycloak:keycloak folio/configure-realms.sh /opt/keycloak/bin/folio/configure-realms.sh
COPY --chown=keycloak:keycloak folio/setup-admin-client.sh /opt/keycloak/bin/folio/setup-admin-client.sh
COPY --chown=keycloak:keycloak folio/start-fips.sh /opt/keycloak/bin/folio/start-fips.sh
COPY --chown=keycloak:keycloak custom-theme /opt/keycloak/themes/custom-theme

USER root
RUN chmod -R 550 /opt/keycloak/bin/folio

USER keycloak

ENTRYPOINT ["/opt/keycloak/bin/folio/start-fips.sh"]
